name:          Code Guide
description:   Front-end các nguyên tắc cơ bản
url:           https://html-runsystem.github.io/front-end-codeguide/

markdown:      rdiscount
permalink:     pretty
pygments:      true
